# Environment name which should equal to Git branch name
develop:

  # SSH user to be used in deployment
  user: www-data
  # Server hostname or IP address for deployment
  hostname: 177.92.144.247
  # Path to deploy.
  deploy_path: /opt/website/

