import type { Service } from "@/types/content";

export const services: Service[] = [
  {
    id: "cloud-infrastructure",
    name: "Cloud and Web Infrastructure",
    icon: "cloud",
    description:
      "Resilient cloud and server environments designed around availability, security, scalability, operational requirements, and cost.",
    capabilities: [
      "Google Cloud Platform",
      "Amazon Web Services",
      "Linux server administration",
      "Docker",
      "Kubernetes",
      "Nginx",
      "Apache",
      "Reverse proxies",
      "Load balancing",
      "CI/CD pipelines",
      "Infrastructure as Code",
      "Monitoring and observability",
      "Security hardening",
      "Backup and recovery",
      "Performance optimization",
    ],
    note: "Architecture is selected based on actual business and technical requirements rather than unnecessary complexity.",
  },
  {
    id: "backend-engineering",
    name: "Backend Engineering",
    icon: "server",
    description:
      "Maintainable and observable backend platforms built to support digital products, internal systems, SaaS applications, and distributed services.",
    capabilities: [
      "Node.js",
      "NestJS",
      "Express",
      "REST APIs",
      "GraphQL APIs",
      "Authentication",
      "Authorization",
      "Webhooks",
      "API gateways",
      "Event-driven systems",
      "Message queues",
      "Background workers",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "Business automation",
      "Third-party integrations",
    ],
    note: "Whostler prioritizes maintainability, security, observability, testability, and operational reliability. Microservices are used only where justified.",
  },
  {
    id: "ai-agentic-systems",
    name: "AI Agentic Systems",
    icon: "bot",
    description:
      "Intelligent backend workflows combining language models, business rules, knowledge retrieval, external tools, and human approval.",
    capabilities: [
      "AI agents",
      "Multi-agent systems",
      "MCP servers",
      "Retrieval-Augmented Generation",
      "Tool calling",
      "Knowledge bases",
      "Semantic search",
      "Document processing",
      "Workflow automation",
      "OpenAI integrations",
      "Human approval workflows",
      "Evaluation and monitoring",
      "Guardrails and permissions",
    ],
    note: "Consequential actions use validation, permissions, logging, and human review where appropriate. AI is never presented as infallible or fully autonomous.",
  },
  {
    id: "relay-integrations",
    name: "Relay and Integration Services",
    icon: "relay",
    description:
      "Secure middleware and integration layers that allow systems, platforms, and data sources to communicate reliably.",
    capabilities: [
      "API integrations",
      "Event relays",
      "Webhook processing",
      "Message queues",
      "Service orchestration",
      "Data synchronization",
      "Data transformation",
      "Retries",
      "Idempotency",
      "Error handling",
      "Integration monitoring",
      "Secure credential management",
    ],
    note: "Integrations connect internal applications, SaaS platforms, CRMs, ERPs, AI services, payment systems, and blockchain networks.",
  },
  {
    id: "blockchain-smart-contracts",
    name: "Blockchain and Smart Contracts",
    icon: "blockchain",
    description:
      "Security-focused smart contract development, review, and testing for Ethereum and EVM-compatible networks.",
    capabilities: [
      "Solidity",
      "Ethereum",
      "EVM-compatible networks",
      "ERC standards",
      "Token contracts",
      "NFT contracts",
      "DAO components",
      "DeFi components",
      "Wallet connectivity",
      "Backend integrations",
      "Hardhat",
      "Foundry",
      "Contract testing",
      "Testnet and mainnet deployment",
    ],
    note: "Security-focused development, review, and testing. We do not claim vulnerability-free contracts or independent audits unless verified.",
  },
  {
    id: "technical-support-sla",
    name: "Technical Support SLA",
    icon: "shield",
    description:
      "Long-term engineering support for organizations operating production infrastructure and software platforms.",
    capabilities: [
      "Infrastructure diagnostics",
      "Application diagnostics",
      "Debugging",
      "Production support",
      "Monitoring",
      "Incident response",
      "Root cause analysis",
      "Maintenance",
      "Security reviews",
      "Performance optimization",
      "Backup verification",
      "Operational documentation",
    ],
    note: "Response targets, service windows, priorities, and commitments depend on the selected SLA agreement.",
  },
  {
    id: "website-development",
    name: "Website Development",
    icon: "globe",
    description:
      "Fast, responsive, and technically robust websites integrated with backend services, APIs, authentication, and cloud infrastructure.",
    capabilities: [
      "Institutional websites",
      "Corporate websites",
      "Landing pages",
      "Documentation websites",
      "Responsive interfaces",
      "Accessibility",
      "Technical SEO",
      "Performance optimization",
      "API integrations",
      "Authentication integrations",
      "Cloud deployment",
    ],
    note: "Complementary to Whostler's backend and cloud engineering capabilities.",
  },
  {
    id: "technical-documentation",
    name: "Technical Documentation",
    icon: "docs",
    description:
      "Clear technical documentation that improves implementation, onboarding, operations, and long-term maintenance.",
    capabilities: [
      "API documentation",
      "Architecture documentation",
      "Integration guides",
      "Knowledge bases",
      "Developer portals",
      "Operational runbooks",
      "Onboarding documentation",
      "Technical articles",
    ],
  },
];
